--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'WIN1252';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: film; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.film (
    id bigint NOT NULL,
    date_sortie date NOT NULL,
    genre character varying(50) NOT NULL,
    titre character varying(150) NOT NULL,
    realisateur_id bigint NOT NULL
);


ALTER TABLE public.film OWNER TO postgres;

--
-- Name: film_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.film ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.film_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.realisateur (
    id bigint NOT NULL,
    nom character varying(255) NOT NULL
);


ALTER TABLE public.realisateur OWNER TO postgres;

--
-- Name: realisateur_genre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.realisateur_genre (
    realisateur_id bigint NOT NULL,
    genre character varying(50) NOT NULL
);


ALTER TABLE public.realisateur_genre OWNER TO postgres;

--
-- Name: realisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.realisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: film; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.film (id, date_sortie, genre, titre, realisateur_id) FROM stdin;
6	2018-01-10	THRILLER	les bronzés	4
7	2018-01-10	COMEDIE	la reine des neiges	5
8	2018-01-10	SCIENCE_FICTION	iron man	3
9	2018-01-10	SCIENCE_FICTION	world war z	4
\.


--
-- Data for Name: realisateur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.realisateur (id, nom) FROM stdin;
3	tarantino
4	michel
5	deniro
6	marcel
7	dorathé
\.


--
-- Data for Name: realisateur_genre; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.realisateur_genre (realisateur_id, genre) FROM stdin;
4	THRILLER
4	SCIENCE_FICTION
4	ACTION
5	COMEDIE
3	SCIENCE_FICTION
\.


--
-- Name: film_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.film_id_seq', 1, false);


--
-- Name: realisateur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.realisateur_id_seq', 7, true);


--
-- Name: film film__titre__uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film__titre__uk UNIQUE (titre);


--
-- Name: film film_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film_pkey PRIMARY KEY (id);


--
-- Name: realisateur realisateur__nom__uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.realisateur
    ADD CONSTRAINT realisateur__nom__uk UNIQUE (nom);


--
-- Name: realisateur_genre realisateur_genre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.realisateur_genre
    ADD CONSTRAINT realisateur_genre_pkey PRIMARY KEY (realisateur_id, genre);


--
-- Name: realisateur realisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.realisateur
    ADD CONSTRAINT realisateur_pkey PRIMARY KEY (id);


--
-- Name: film film__realisateur_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film__realisateur_fk FOREIGN KEY (realisateur_id) REFERENCES public.realisateur(id);


--
-- Name: realisateur_genre realisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.realisateur_genre
    ADD CONSTRAINT realisateur_id FOREIGN KEY (realisateur_id) REFERENCES public.realisateur(id);


--
-- PostgreSQL database dump complete
--

