--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'WIN1252';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS mega_movies;
--
-- Name: mega_movies; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE mega_movies WITH TEMPLATE = template0 ENCODING = 'WIN1252' LOCALE = 'French_France.1252';


ALTER DATABASE mega_movies OWNER TO postgres;

\connect mega_movies

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'WIN1252';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: film; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.film (
    id bigint NOT NULL,
    date_sortie date NOT NULL,
    genre character varying(255) NOT NULL,
    titre character varying(150) NOT NULL,
    realisateur_id bigint NOT NULL
);


ALTER TABLE public.film OWNER TO postgres;

--
-- Name: film_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.film ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.film_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: realisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.realisateur (
    id bigint NOT NULL,
    nom character varying(255) NOT NULL
);


ALTER TABLE public.realisateur OWNER TO postgres;

--
-- Name: realisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.realisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.realisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: film; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.film (id, date_sortie, genre, titre, realisateur_id) FROM stdin;
6	2018-01-10	THRILLER	dfsdfsdfsd	1
7	2018-01-10	COMEDIE	fff	2
8	2018-01-10	SCIENCE_FICTION	sss	3
9	2018-01-10	SCIENCE_FICTION	eaeeaeae	1
\.


--
-- Data for Name: realisateur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.realisateur (id, nom) FROM stdin;
1	deniro
2	dorcel
3	dorathé
\.


--
-- Name: film_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.film_id_seq', 1, false);


--
-- Name: realisateur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.realisateur_id_seq', 1, false);


--
-- Name: film film__titre__uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film__titre__uk UNIQUE (titre);


--
-- Name: film film_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film_pkey PRIMARY KEY (id);


--
-- Name: realisateur realisateur__nom__uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.realisateur
    ADD CONSTRAINT realisateur__nom__uk UNIQUE (nom);


--
-- Name: realisateur realisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.realisateur
    ADD CONSTRAINT realisateur_pkey PRIMARY KEY (id);


--
-- Name: film film__realisateur_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.film
    ADD CONSTRAINT film__realisateur_fk FOREIGN KEY (realisateur_id) REFERENCES public.realisateur(id);


--
-- PostgreSQL database dump complete
--

